steps:
  # Build the Python worker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/python-worker:latest', './deploy/worker']

  # Build the Go Orchestrator image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/code-sandbox:latest', '.']

  # Push the images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/python-worker:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/code-sandbox:latest']

images:
  - 'gcr.io/$PROJECT_ID/python-worker:latest'
  - 'gcr.io/$PROJECT_ID/code-sandbox:latest'

options:
  logging: CLOUD_LOGGING_ONLY
